#!/bin/sh

DAEMON=/sbin/udhcpd
NAME=udhcpd
PIDFILE=/var/run/udhcpd

INIT=/etc/init.d/udhcpd
OPTIONS=""

#. /etc/default/dhcp
INTERFACES="eth0"

[ -z "$INTERFACES" ] && exit 0

test -x $DAEMON || exit 0

case "$1" in
  start)
    for iface in $INTERFACES; do
      if [ -f /etc/udhcpd/udhcpd.$iface.conf ]; then
        echo -n "Starting $NAME on $iface: "
        $DAEMON /etc/udhcpd/udhcpd.$iface.conf
      else
        echo "Skipping $iface (no /etc/udhcpd/udhcpd.$iface.conf)"
      fi
    done
    ;;
  stop)
    for iface in $INTERFACES; do
      echo -n "Stopping $NAME on $iface: "
      start-stop-daemon --stop --quiet --pidfile $PIDFILE.$iface.pid --name $NAME
      echo "done."
    done
    ;;
  restart)
    echo -n "Restarting $NAME: "
    $INIT stop > /dev/null 2>&1
    $INIT start > /dev/null 2>&1
    echo "$NAME. "
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
