#!/bin/sh
#
# Manage radaq leds
#
# 130420 kongo <kongo@etf.nu>

case "$1" in
  start)
        echo -n "Setting leds: "
        i2cset -y 0 3 1 2
        echo "OK"
        ;;
  stop)
        echo -n "Setting leds: "
        i2cset -y 0 3 1 0
        echo "OK"
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

