#!/bin/sh
#
# Manage radaq driver
#
# 130420 kongo <kongo@etf.nu>

case "$1" in
  start)
        echo -n "Starting radaq: "
        modprobe radaq
        echo "OK"
        ;;
  stop)
        echo -n "Stopping radaq: "
        rmmod radaq
        echo "OK"
        ;;
  restart|reload)
        modprobe radaq
        rmmod radaq
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

